version: '3.7'
services:
  app:
    image: atif/kafka-sample
    container_name: kafka_sample_app
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - "mysql:mysql"
      - "kafka:kafka"
      - "redis:redis"
    depends_on:
      - mysql
      - kafka
      - redis
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_server
    links:
      - "zookeeper:zookeeper"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mysql:
    image: mysql/mysql-server
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: trending
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin-password
      MYSQL_ROOT_PASSWORD: root-password
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis_server
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_server
    ports:
      - "2181:2181"