version: '3.7'
services:
  app:
    image: atif/kafka-sample
    ports:
      - "8080:8080"
    expose:
      - "8080"
    links:
      - mysql:mysql
      - kafka:kafka
      - redis:redis
    depends_on:
      - mysql
      - kafka
      - redis
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_server
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mysql:
    image: mysql/mysql-server:5.7
    container_name: mysql_server_5_7
    environment:
      MYSQL_DATABASE: trending
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin-password
      MYSQL_ROOT_PASSWORD: root-password
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_server
    ports:
      - "2181:2181"